name: cellpose
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - setuptools
  - bioimageio.core
  - imagecodecs
  - cellpose=3.1.0
  - pip:
      - matplotlib
      - tqdm
